### PR TITLE
Add intellij instructions and link to revealjs example

### PR DESCRIPTION
**Pull request by danhyun**

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master

**Comment by danhyun** [comment]
Np, what do you think about #6? If you like the idea I can add a gradle task that will publish all outputs to the `gh-pages` branch so that the users have something they can see a la http://mojavelinux.github.io/decks/

**Comment by rwinch** [comment]
If you have time to put a PR to together, I'd love to accept it. Perhaps at that point it makes sense to integrate with Travis (or some other CI server). Thoughts?

**Comment by danhyun** [comment]
Actually a CI would make sense to auto-generate the gh-pages.
We could just have it listen on pushes to master and pull down master and
run asciidoctor on them, commit, and publish.

On Mon, Feb 23, 2015 at 11:33 AM, Rob Winch <notifications@github.com>
wrote:

> If you have time to put a PR to together, I'd love to accept it. Perhaps
> at that point it makes sense to integrate with Travis (or some other CI
> server). Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rwinch/asciidoctor-gradle-examples/pull/7#issuecomment-75577668>
> .
>



-- 
Thanks,

Daniel Hyun
blog: http://hyunlabs.com/

**Comment by rwinch** [comment]
Precisely what I was thinking (sorry I wasn't very clear). I'll create a separate task (#6) for that.

**Pull request merged**
