### PR TITLE
fix Kindlegen download for Linux

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Not the prettiest way to fix it, but it gets the job done.

**Comment by mojavelinux** [comment]
I also recommend renaming the folder to asciidoc-to-kf8-example. Using both epub3 and kf8 is redundant as kf8 is a (bastardized) type of epub3.

**Comment by rwinch** [comment]
Thanks merged!

The reason I have it as epub3-kf8 is because eventually the sample will output both formats since that was what was requested in asciidoctor/asciidoctor-gradle-examples/issues/13

**Comment by mojavelinux** [comment]
Oh, I see. I was thinking you were creating a parallel project instead. Once you merge it upstream, I recommend simply using the name "epub3" or, if you want to keep it more generic, "ebook".

**Pull request merged**
